### ISSUE TITLE
No results returns "Unexpected Error"

### ISSUE THREAD

**Issue by seanstaley** [seanstaley/database-query-plugin#18]
## Replicate:
1. Find a table without any contents
2. Perform a SELECT on that table
3. Notice the error.
## Stack Trace:

> [INFO] [talledLocalContainer] 2012-10-07 12:09:26,319 [http-8080-6] [:admin] ERROR com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor - Index: 0, Size: 0
> [INFO] [talledLocalContainer] java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
> [INFO] [talledLocalContainer]     at java.util.ArrayList.RangeCheck(ArrayList.java:547)
> [INFO] [talledLocalContainer]     at java.util.ArrayList.get(ArrayList.java:322)
> [INFO] [talledLocalContainer]     at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:448)
> [INFO] [talledLocalContainer]     at com.jivesoftware.plugin.dbQuery.dao.query.QueryExecute.retrieveColumnNames(QueryExecute.java:68)
> [INFO] [talledLocalContainer]     at com.jivesoftware.plugin.dbQuery.dao.query.QueryExecute.formatResults(QueryExecute.java:86)
> [INFO] [talledLocalContainer]     at com.jivesoftware.plugin.dbQuery.dao.query.QueryExecute.returnQueryResults(QueryExecute.java:114)
> [INFO] [talledLocalContainer]     at com.jivesoftware.plugin.dbQuery.action.query.RunQueryAction.execute(RunQueryAction.java:50)

**Comment by seanstaley** [comment]
Does the trick!
